### ISSUE TITLE
Determine how to handle Admin Users in production

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/gw-sufia#101]
How do we want to handle admin access in production since we do not have access to LDAP groups?

**Comment by kerchner** [comment]
@ihardy is looking into creating an LDAP group that we can reference similar to https://github.com/psu-stewardship/scholarsphere/blob/develop/app/models/ability.rb#L10

**Comment by kerchner** [comment]
@kilahimm after LDAP group is created, feel free to try making the change to ability.rb .  You can reassign to me if that doesn't work.

**Comment by kilahimm** [comment]
We have access to the isMemberOf attribute as of this afternoon, I'm working on integrating this into gw-sufia.

**Comment by kerchner** [comment]
Great, let me know if I can be of help.
