### ISSUE TITLE
Replace Open Access Label with Public Access

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/gw-sufia#117]
Recommendation from Hope to replace the Open Access label with Public Access.  Licenses provided within Sufia do not meet the gold-standard for open access and we shouldn't represent it as such.

**Comment by kerchner** [comment]
Initial investigation yielded the following:
- Adding a value of ```sufia.visbility.open: "Public Access"``` into config/locales/en.yml configures the label on /dashboard/files and on /files/my-object-id 
- However, there are a number of places where this is hard-coded in Sufia.  One is the Permissions tab of files/my-object-id/edit and a search of the code in the sufia repo reveals other potential locations.  Next step is to open a ticket with projecthydra/sufia and submit a PR that substitutes these instances of "Open Access" with ```t('sufia.visibility.open')``` as appropriate.
Recommendation is to not configure sufia.visibility.open until aforementioned PR becomes part of the sufia code base; configuring it right now will introduce inconsistencies across the UI.

**Comment by kilahimm** [comment]
Now that the open access policy has been approved I think we shouldn't pursue this, thoughts?

**Comment by kerchner** [comment]
Per discussion with @kilahimm marking this as a wontfix.  Although it's true that the label is hard-coded in some places and configurable in others, it does not appear that other institutions are configuring/overriding the label, so it does not need to be our priority to fix this.
