### ISSUE TITLE
Update locales for app name

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/gw-sufia#118]
Final Name: GW Scholar Space

**Comment by kerchner** [comment]
@kilahimm do I get a prize?

**Comment by kerchner** [comment]
@kilahimm you and Robin D. are aware of these, right?

http://scholarspace.manoa.hawaii.edu/
http://scholarspace.jccc.edu/

**Comment by kilahimm** [comment]
@kerchner confirmed with Robin D that we are OK to go ahead with the name.  Will use: GW ScholarSpace.  I've updated the PR accordingly.

**Comment by kilahimm** [comment]
Completed with PR #119
