### ISSUE TITLE
Title of logout page is "GW Libraries Bootswatch"

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/gw-sufia#127]
Change this to a better title.

**Comment by ihardy** [comment]
Changed to GW ScholarSpace Sign Out. This file isn't tracked here so for the record, I change the page title in shibboleth/localLogout.html

**Comment by kerchner** [comment]
Verified that this is now resolved (applies to production as well as test).

**Comment by kerchner** [comment]
@ihardy please change in https://github.com/gwu-libraries/shibboleth/blob/master/etc/shibboleth/localLogout.html as well.

**Comment by ihardy** [comment]
@kerchner I'll change the name in the shib repo to localLogout.html.template and update the instructions to include customizing the file.
