### ISSUE TITLE
creating meaningful log-out html for shibboleth session

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/gw-sufia#97]
Create a meaningful log-out landing page for shibboleth sessions.  Current page is very vanilla.  Recommend a standard page for all GWL shibboleth enabled apps.

**Comment by kerchner** [comment]
Assigning to @kilahimm - Add the HTML file to https://github.com/gwu-libraries/shibboleth/tree/master/etc/shibboleth  and call it localLogout.html .  Add configuration step into https://github.com/gwu-libraries/shibboleth/blob/master/README.md

**Comment by kilahimm** [comment]
I uploaded the template localLogout.html file to the shibboleth repo and updated the readme to reflect the settings to customize.
